ALTER TABLE cars
  ADD COLUMN dealership_id INTEGER;

UPDATE cars
  SET dealership_id = 1
  WHERE dealership_id IS NULL;

ALTER TABLE cars
  ALTER COLUMN dealership_id
  SET NOT NULL;

ALTER TABLE cars
  ADD CONSTRAINT dealership_fk FOREIGN KEY (dealership_id)
  REFERENCES dealerships(id);

ALTER TABLE cars
  ALTER COLUMN brand SET NOT NULL,
  ALTER COLUMN model SET NOT NULL,
  ALTER COLUMN year SET NOT NULL,
  ALTER COLUMN price SET NOT NULL,
  ALTER COLUMN color SET NOT NULL,
  ALTER COLUMN condition SET NOT NULL,
  ALTER COLUMN sold SET NOT NULL;